Ratings & Reviews PR
rfe5-fec5-sedna/FEC pull request #23
Opened 2021-09-17 19:12 UTC by jordanvillacorta

Major changes:

- Add average star rating functionality
- Add recommend percentage functionality
- Add conditionals to catch if there are no recommendations or if percentage is NaN.
- Add CSS file for future styling
- Add properties to RatingsBreakdown state
- Add functions to helperFunction

2021-09-17 19:18 UTC, SebasCC99 commented on client/src/ratings_reviews/RatingsBreakdown.jsx
> +  componentDidUpdate(prevProps) {
please fix the indentation of lines

2021-09-17 19:22 UTC, SebasCC99 commented on client/src/ratings_reviews/ReviewsList.jsx
>    componentDidUpdate(prevProps) {
please fix the indentation

2021-09-17 20:14 UTC, SebasCC99 requested changes
Please map in reviews list, render a review tile for each review

2021-09-17 23:46 UTC, jordanvillacorta commented on client/src/ratings_reviews/RatingsBreakdown.jsx
> +  componentDidUpdate(prevProps) {
Fixed!

2021-09-17 23:46 UTC, jordanvillacorta commented on client/src/ratings_reviews/ReviewsList.jsx
>    componentDidUpdate(prevProps) {
Fixed!

2021-09-18 00:49 UTC, SebasCC99 approved these changes
Nice job! Looking more organized and clean!

2021-09-18 02:25 UTC, merged